module Shell::AutoComplete
  VERSION = "0.1.0"
end

require "./shell-auto_complete/candidate"
require "./shell-auto_complete/completion_context"
require "./shell-auto_complete/annotations"
require "./shell-auto_complete/errors"
require "./shell-auto_complete/help"
require "./shell-auto_complete/command"
require "./shell-auto_complete/parser"
require "./shell-auto_complete/macros/command"
require "./shell-auto_complete/macros/flag"
require "./shell-auto_complete/macros/positional"
require "./shell-auto_complete/transformers/string"
require "./shell-auto_complete/transformers/numeric"
require "./shell-auto_complete/transformers/path"
require "./shell-auto_complete/transformers/stdlib"
require "./shell-auto_complete/transformers/enum"
require "./shell-auto_complete/transformers/collection"
