module Shell::AutoComplete
  VERSION = "0.9.0"
end

require "./shell-auto_complete/candidate"
require "./shell-auto_complete/completion_context"
require "./shell-auto_complete/annotations"
require "./shell-auto_complete/errors"
require "./shell-auto_complete/help"
require "./shell-auto_complete/command"
require "./shell-auto_complete/completion/install_flag"
require "./shell-auto_complete/completion/bash"
require "./shell-auto_complete/completion/zsh"
require "./shell-auto_complete/completion/fish"
require "./shell-auto_complete/completion/dispatcher"
require "./shell-auto_complete/parser"
require "./shell-auto_complete/macros/command"
require "./shell-auto_complete/macros/flag"
require "./shell-auto_complete/macros/positional"
require "./shell-auto_complete/transformers/string"
require "./shell-auto_complete/transformers/numeric"
require "./shell-auto_complete/transformers/char"
require "./shell-auto_complete/transformers/path"
require "./shell-auto_complete/transformers/stdlib"
require "./shell-auto_complete/transformers/enum"
require "./shell-auto_complete/transformers/collection"
require "./shell-auto_complete/types/positive_int"
require "./shell-auto_complete/types/non_negative_int"
require "./shell-auto_complete/types/percentage"
require "./shell-auto_complete/types/epoch_time"
require "./shell-auto_complete/types/date"
require "./shell-auto_complete/types/env_var"
